"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

"files": [
  {
    "source": "/packages/marketplace/messages/en.json",
    "translation": "/packages/marketplace/messages/%two_letters_code%.json"
  },
  {
    "source": "/packages/marketplace/content/legal/en/*.mdx",
    "translation": "/packages/marketplace/content/legal/%two_letters_code%/%original_file_name%"
  },
  {
    "source": "/packages/marketplace/content/help/en/*.mdx",
    "translation": "/packages/marketplace/content/help/%two_letters_code%/%original_file_name%"
  }
]
